# Generated by Django 4.1.2 on 2022-10-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Aser', models.IntegerField(unique=True)),
                ('Pser', models.IntegerField()),
                ('Aname', models.TextField()),
                ('Aphone', models.TextField()),
                ('Atel', models.TextField()),
                ('Adate', models.DateField()),
                ('ServNo', models.IntegerField()),
                ('Arem', models.TextField()),
                ('Arraive', models.BooleanField()),
                ('DocNo', models.IntegerField()),
                ('DocName', models.TextField()),
                ('Fees', models.IntegerField()),
                ('Cost', models.IntegerField()),
                ('Seen', models.BooleanField()),
                ('DoneBy', models.TextField()),
                ('Per', models.IntegerField()),
                ('AMPMCode', models.TextField()),
                ('AMPM', models.TextField()),
                ('ContrC', models.IntegerField()),
                ('MoneyBy', models.TextField()),
                ('MoneyNo', models.IntegerField()),
            ],
        ),
    ]
