# Generated by Django 4.1.2 on 2022-10-13 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='AMPM',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='AMPMCode',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Adate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Aname',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Aphone',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Arem',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Arraive',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Aser',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Atel',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='ContrC',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Cost',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='DocName',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='DocNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='DoneBy',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Fees',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='MoneyBy',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='MoneyNo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Per',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Pser',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Seen',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='ServNo',
            field=models.IntegerField(null=True),
        ),
    ]
