# Generated by Django 4.1.2 on 2022-10-15 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0002_alter_appointments_ampm_alter_appointments_ampmcode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Ser', models.IntegerField(null=True, unique=True)),
                ('Pname', models.TextField(null=True)),
                ('BirthDate', models.DateField(null=True)),
                ('Sex', models.TextField(null=True)),
                ('Job', models.TextField(null=True)),
                ('Mstatus', models.TextField(null=True)),
                ('Street', models.TextField(null=True)),
                ('Phone', models.TextField(null=True)),
                ('Mobile', models.TextField(null=True)),
                ('Addmision', models.DateField(null=True)),
                ('ContC', models.IntegerField(null=True)),
                ('ContN', models.TextField(null=True)),
                ('Ref', models.TextField(null=True)),
                ('Co', models.TextField(null=True)),
                ('Pro', models.TextField(null=True)),
                ('DELT', models.BooleanField(null=True)),
                ('PatNote', models.TextField(null=True)),
            ],
        ),
    ]
