# Generated by Django 4.1.2 on 2022-10-15 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0003_patient'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='Addmision',
            new_name='Admission',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='Pname',
            new_name='PName',
        ),
    ]
