# Generated by Django 4.1.2 on 2022-10-16 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0004_rename_addmision_patient_admission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='AMPM',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='AMPMCode',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Adate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Aname',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Aphone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Arem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Arraive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Atel',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='ContrC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Cost',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='DocName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='DocNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='DoneBy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Fees',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='MoneyBy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='MoneyNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Per',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Pser',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='Seen',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='ServNo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Admission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='BirthDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Co',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ContC',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='ContN',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='DELT',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Job',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Mobile',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Mstatus',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PName',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='PatNote',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Phone',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Pro',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Ref',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Sex',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Street',
            field=models.TextField(blank=True, null=True),
        ),
    ]
