# Generated by Django 4.1.2 on 2022-10-17 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0005_alter_appointments_ampm_alter_appointments_ampmcode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='DocName',
            field=models.TextField(blank=True, choices=[('manal', 'دكتورة منال ابو الفضل'), ('tamer', 'دكتور تامر الشربيني'), ('maged', 'د. ماجد احمد عبد الفتاح'), ('3elwy', 'أحمد علوي بشارة'), ('mona', 'د. منى أحمد أبوالفضل'), ('7asna2', 'دكتورة حسناء فكري'), ('ranya', 'دكتورة رانيا غازي'), ('wala2', 'دكتورة ولاء محمود فودة')], default='manal', null=True),
        ),
    ]
