# Generated by Django 4.1.2 on 2022-10-17 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0006_alter_appointments_docname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='Arraive',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
