# Generated by Django 4.1.2 on 2022-10-17 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0007_alter_appointments_arraive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='DoneBy',
            field=models.TextField(blank=True, choices=[('MahmoudAboulfadl', 'MahmoudAboulfadl'), ('MohamedTamer', 'MohamedTamer')], default='MahmoudAboulfadl', null=True),
        ),
    ]
