# Generated by Django 4.1.2 on 2022-10-17 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0008_alter_appointments_doneby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='MoneyBy',
            field=models.TextField(blank=True, choices=[('MahmoudAboulfadl', 'MahmoudAboulfadl'), ('MohamedTamer', 'MohamedTamer')], default='MahmoudAboulfadl', null=True),
        ),
    ]
