# Generated by Django 4.1.2 on 2022-11-17 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0009_alter_appointments_moneyby'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='Paid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
