# Generated by Django 4.1.2 on 2022-11-18 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0010_appointments_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='ShouldPay',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
