# Generated by Django 4.1.2 on 2022-11-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0011_appointments_shouldpay'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='Debts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='ShouldPay',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
