# Generated by Django 4.1.2 on 2022-11-28 15:48

import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0012_patient_debts_alter_appointments_shouldpay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Debts',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Paid_Amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('Date', models.DateField(default=datetime.date.today)),
                ('Appointment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='MainMenu.appointments')),
            ],
        ),
    ]
