# Generated by Django 4.1.2 on 2022-11-28 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0013_alter_patient_debts_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Debts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
