# Generated by Django 4.1.2 on 2022-11-29 21:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0014_alter_patient_debts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Service Name')),
                ('price', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Service Price')),
                ('cost', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Service Cost')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Doctor Name')),
                ('services', models.ManyToManyField(to='MainMenu.services', verbose_name='Services')),
            ],
        ),
    ]
