# Generated by Django 4.1.2 on 2022-11-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0015_services_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='bakcendname',
            field=models.CharField(max_length=50, null=True, verbose_name='Backend Name'),
        ),
    ]
