# Generated by Django 4.1.2 on 2022-11-29 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0016_doctor_bakcendname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='DocName',
            field=models.TextField(blank=True, choices=[('manal', 'دكتورة منال ابو الفضل')], default='manal', null=True),
        ),
    ]
