# Generated by Django 4.1.2 on 2022-12-07 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0018_alter_appointments_arem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='Arem',
            field=models.TextField(blank=True, choices=[('كشف', '(كشف) 200 L.E')], default='كشف', null=True),
        ),
    ]
