# Generated by Django 4.1.2 on 2022-12-08 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0019_alter_appointments_arem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='Arem',
            field=models.TextField(blank=True, choices=[('كشف', '(كشف) 200 L.E'), ('استشارة', '(استشارة) 50 L.E'), ('متابعة', '(متابعة) 75 L.E')], default='كشف', null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='DocName',
            field=models.TextField(blank=True, choices=[('manal', 'دكتورة منال ابو الفضل'), ('tamer', 'دكتور تامر الشربيني')], default='manal', null=True),
        ),
    ]
