# Generated by Django 4.1.2 on 2022-12-09 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0020_alter_appointments_arem_alter_appointments_docname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Sex',
            field=models.TextField(blank=True, choices=[('M', 'ذكر'), ('F', 'أنثى')], default='M', null=True),
        ),
    ]
