# Generated by Django 4.1.2 on 2023-06-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0021_alter_patient_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Sex',
            field=models.TextField(blank=True, choices=[('ذكر', 'ذكر'), ('أنثى', 'أنثى')], default='ذكر', null=True),
        ),
    ]
