# Generated by Django 4.1.2 on 2023-06-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0022_alter_patient_sex'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='DocName',
            field=models.TextField(blank=True, choices=[('دكتورة منال ابو الفضل', 'دكتورة منال ابو الفضل'), ('دكتور تامر الشربيني', 'دكتور تامر الشربيني')], default='دكتورة منال ابو الفضل', null=True),
        ),
    ]
