# Generated by Django 4.1.2 on 2023-06-19 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0023_alter_appointments_docname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='bakcendname',
        ),
    ]
