# Generated by Django 4.1.2 on 2023-07-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0024_remove_doctor_bakcendname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='Arem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='DocName',
            field=models.TextField(blank=True, default='دكتورة منال ابو الفضل', null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='DoneBy',
            field=models.TextField(blank=True, default='MahmoudAboulfadl', null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='MoneyBy',
            field=models.TextField(blank=True, default='MahmoudAboulfadl', null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='Sex',
            field=models.TextField(blank=True, default='ذكر', null=True),
        ),
    ]
