# Generated by Django 4.1.2 on 2023-07-16 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainMenu', '0025_alter_appointments_arem_alter_appointments_docname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payments',
            name='MoneyBy',
            field=models.TextField(blank=True, null=True),
        ),
    ]
