# Generated by Django 4.2.17 on 2025-01-23 15:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("MainMenu", "0026_payments_moneyby"),
    ]

    operations = [
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Type",
                    models.CharField(
                        choices=[
                            ("UTIL", "Utility Bills"),
                            ("NET", "Internet Bill"),
                            ("TEL", "Telephone Bill"),
                            ("FDWTR", "Food / Water Resupply"),
                            ("TXC", "Toxic Wastes"),
                            ("MRKT", "Marketing"),
                            ("CNSM", "Consumables"),
                            ("MOB", "Mobile Phone Bills"),
                            ("NC", "Not Categorized"),
                        ],
                        default=("NC", "Not Categorized"),
                        max_length=5,
                        verbose_name="Type of Resource",
                    ),
                ),
                (
                    "Name",
                    models.CharField(max_length=200, verbose_name="Resource Name"),
                ),
                (
                    "Counter",
                    models.CharField(
                        default="items", max_length=50, verbose_name="Counter"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.TextField(verbose_name="Supplier Name")),
            ],
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "AmountOfItem",
                    models.DecimalField(
                        decimal_places=2, max_digits=20, verbose_name="Amount"
                    ),
                ),
                (
                    "Price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=50,
                        verbose_name="Price of Resource",
                    ),
                ),
                (
                    "AmountPaid",
                    models.DecimalField(
                        decimal_places=2, max_digits=50, verbose_name="Paid"
                    ),
                ),
                ("Date", models.DateField()),
                (
                    "ReceiptID",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="ID of Receipt"
                    ),
                ),
                (
                    "ItemPaidFor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="MainMenu.resource",
                        verbose_name="Resource bought",
                    ),
                ),
                (
                    "Supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="MainMenu.supplier",
                        verbose_name="Supplier",
                    ),
                ),
            ],
        ),
    ]
