# Generated by Django 4.2.17 on 2025-01-23 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("MainMenu", "0027_resource_supplier_expense"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="Price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=50,
                null=True,
                verbose_name="Price of Resource",
            ),
        ),
    ]
